set FEEDBACK OFF
set LINESIZE 32767
set PAGESIZE 0
set underline off
set COLSEP |
set TRIM ON
set TRIMS ON
set HEADING OFF
set TERMOUT OFF
spool timezone.out
select
TIMEZONEID,
BIAS,
DAYLIGHTBIAS,
STANDARDTIMEADJMONTH,
STANDARDTIMEADJDAYOFWEEK,
STANDARDTIMEADJDAY,
STANDARDTIMEADJHOUR,
STANDARDTIMEADJMINUTE,
STANDARDNAMEABREVIATION,
STANDARDNAME,
DAYLIGHTTIMEADJMONTH,
DAYLIGHTTIMEADJDAYOFWEEK,
DAYLIGHTTIMEADJDAY,
DAYLIGHTTIMEADJHOUR,
DAYLIGHTTIMEADJMINUTE,
DAYLIGHTNAMEABREVIATION,
DAYLIGHTNAME
from timezone;
spool off;
quit
